services:
  api:
    build:
      context: api/
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/app
    depends_on:
      - db
    networks:
      - network

  db:
    build:
      context: dev-database/
    ports:
      - "3306:3306"
    networks:
      - network

networks:
  network: