services:
  api:
    build:
      context: api/
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/app
    networks:
      - link-shortener-network

  db:
    build:
      context: dev-database/
    ports:
      - "3306:3306"
    networks:
      - link-shortener-network

networks:
  link-shortener-network: